//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lr11_13.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TheaterEntities : DbContext
    {
        public TheaterEntities()
            : base("name=TheaterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Актеры> Актеры { get; set; }
        public virtual DbSet<Афиша> Афиша { get; set; }
        public virtual DbSet<ЗП_актеров> ЗП_актеров { get; set; }
        public virtual DbSet<Контракты> Контракты { get; set; }
        public virtual DbSet<Постановка> Постановка { get; set; }
        public virtual DbSet<Роли_актеров> Роли_актеров { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
    }
}
