//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lr11_13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Актеры
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Актеры()
        {
            this.Контракты = new HashSet<Контракты>();
            this.Роли_актеров = new HashSet<Роли_актеров>();
        }
    
        public int id_сотрудника { get; set; }
        public string Стаж_работы { get; set; }
        public string Последняя_постановка { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Контракты> Контракты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Роли_актеров> Роли_актеров { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
