//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lr11_13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Афиша
    {
        public int id_афиши { get; set; }
        public int id_постановки { get; set; }
        public int Кол_во_билетов { get; set; }
        public int id_главной_роли { get; set; }
        public int Цена_билета { get; set; }
        public System.DateTime Дата_и_время_проведения { get; set; }
    
        public virtual Роли_актеров Роли_актеров { get; set; }
        public virtual Постановка Постановка { get; set; }
    }
}
