//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lr11_13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Контракты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Контракты()
        {
            this.ЗП_актеров = new HashSet<ЗП_актеров>();
        }
    
        public int id_контракта { get; set; }
        public int id_актера { get; set; }
        public System.DateTime Дата_заключения_контракта { get; set; }
        public string Data { get => Дата_заключения_контракта.ToString("dd.MM.yyyy"); }
        public string Название_постановки { get; set; }
        public System.DateTime Дата_окончания_контракта { get; set; }
        public string Data1 { get => Дата_окончания_контракта.ToString("dd.MM.yyyy"); }
        public int Выплаты_в_месяц { get; set; }
    
        public virtual Актеры Актеры { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗП_актеров> ЗП_актеров { get; set; }
    }
}
