//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lr11_13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Роли_актеров
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Роли_актеров()
        {
            this.Афиша = new HashSet<Афиша>();
        }
    
        public int id_роли { get; set; }
        public string Название_роли { get; set; }
        public int id_актера { get; set; }
        public int id_постановки { get; set; }
    
        public virtual Актеры Актеры { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Афиша> Афиша { get; set; }
        public virtual Постановка Постановка { get; set; }
    }
}
